### PR TITLE
Update _form.html.erb

### PR DESCRIPTION
**Pull request by iqre8**
Prevent people from uploading excel files.
Who is people? We are people....

### CODE REVIEW

**Review by iqre8 — COMMENTED** [review]
Sorry for missing the closing "

**Comment by jarednorman** [comment]
Bad news: Windows machines with Excel installed will sometimes send CSVs with a propriety MIME that will ruin your day, `application/vnd.ms-excel`. You might be thinking, "wait, that doesn't even say it's a CSV," and sadly, you're right. It doesn't. We've seen this issue with other CSV handling systems. 😒

I'd love to find a good solution for both this issue as well as #55 so that we can be better friends with people using Excel and live in harmony.

**Comment by kennyadsl** [comment]
@iqre8 what about doing this on the server-side instead?

**Comment by iqre8** [comment]
@kennyadsl I would prefer it be done on both sides. Client side would reduce the amount of 'errors' caused.  And server-side would primarily be needed to stop malicious attempts.
It certainly won't make the app noticable slower on the client side.

**Pull request closed without merging**
